baseURL = "https://thesespieces.course.sjmd.space"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Module 5"
theme = "teach"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
relativeURLs = true

[params]
	editURL = "https://github.com/sjmd/thesespieces/tree/master/content/"
	helpURL = "https://sjmd.space/help"
	description = "Social Justice, Minus Dogma Course Module 5"
	author = "SJMD"
	showVisitedLinks = true
	disableBreadcrumb = false
	disableNextPrev = false
	themeVariant = "purple"

[outputs]
	home = [ "HTML", "RSS", "JSON"]
