# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Teach"
license = "MIT"
description = "Online course theme for Hugo, a simplified version of the Hugo Learn Theme by Mathieu Cornic, which was based on Grav Learn theme"
tags = ["documentation", "grav", "teach", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search"]
min_version = 0.25

[author]
  name = "Sam Killermann"
  homepage = "https://samuelkillermann.com"

[original]
  name = "Hugo Learn Theme"
  homepage = "https://github.com/matcornic/hugo-theme-learn/"
  repo = "https://github.com/matcornic/hugo-theme-learn"
